// DO NOT EDIT THIS FILES
// THIS FILE IS GENERATE FROM `unplugin-environment` - see https://npm.im/unplugin-environment

declare module "@env" {
	export const env: {
		REACT_APP_NAME: string;
		REACT_APP_DURATION: number;
	};
}
