name: Main Pipeline

on:
  pull_request:
  push:
    branches: [main, beta]

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
           contents: "write" # to be able to publish a GitHub release
           issues: "write" # to be able to comment on released issues
           pull-requests: "write" # to be able to comment on released pull requests
           id-token: "write" # to enable use of OIDC for npm provenance

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_USER: 'anakmagang'
      GIT_AUTHOR_NAME: "anakmagang"
      GIT_COMMITTER_NAME: "anakmagang"
      GIT_AUTHOR_EMAIL: "contact@evilfactorylabs.org"
      GIT_COMMITTER_EMAIL: "contact@evilfactorylabs.org"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Using corepack
        run: corepack enable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install --immutable

      - name: Print dependencies versions
        run: |
          for i in "node" "yarn" "git" "yarn commitlint"
          do
            echo "$i version: $($i --version)"
          done

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: yarn commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: yarn commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build

      - name: test
        run: yarn test

      - name: release
        run: yarn release
