name: Main Pipeline

on:
  push:
    branches: [main, beta]

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
           contents: "write" # to be able to publish a GitHub release
           issues: "write" # to be able to comment on released issues
           pull-requests: "write" # to be able to comment on released pull requests
           id-token: "write" # to enable use of OIDC for npm provenance

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_USER: 'anakmagang'
      GIT_AUTHOR_NAME: "anakmagang"
      GIT_COMMITTER_NAME: "anakmagang"
      GIT_AUTHOR_EMAIL: "contact@evilfactorylabs.org"
      GIT_COMMITTER_EMAIL: "contact@evilfactorylabs.org"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Using corepack
        run: corepack enable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install --immutable

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build

      - name: test
        run: yarn test

      - name: release
        run: yarn release
